### ISSUE TITLE
Export fails with foreign playlists

### ISSUE THREAD

**Issue by baszero** [bitsofpancake/spotify-backup#1]
I use many playlists in my account which I created myself.
However, there also many playlists that I am following.

It seems that this script fails when it tries to export those.

Question: 
- Can this be fixed? (I don't know how to code python)
- Playlists where I'm not the owner of should not get exported (my opinion).

Great tool however!! 

Thanks

Here is the error stack trace:

```
[08:25:08] Loading playlist: Armin van Buuren - A State Of Trance Radio Episodes (NEW: ASOT 708) (3285 songs)
Traceback (most recent call last):
  File "spotify-backup.py", line 162, in <module>
    main()
  File "spotify-backup.py", line 139, in main
    playlist['tracks'] = spotify.list(playlist['tracks']['href'], {'limit': 100})
  File "spotify-backup.py", line 44, in list
    response = self.get(response['next'])
  File "spotify-backup.py", line 31, in get
    return json.load(urllib2.urlopen(req))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 7042 column 23 (char 327243)
```

**Comment by jonasbits** [comment]
I have the same problem when using the python 2.7 compatible version of the script. But when I use the
"--format json" parameter it goes all the way to the finish.

**Comment by henriksten65** [comment]
The name of my Spotify account starts with the swedish letter "å" which results in this error:

Logged in as åabcdef (åabcdef)
Loading playlists...
Couldn't load URL: https://api.spotify.com/v1/users/åabcdef/playlists?limit=50 ('ascii' codec can't encode character '\xe5' in position 14: ordinal not in range(128))

(Here I have changed the user name but kept the first letter.)
