### ISSUE TITLE
IncompleteRead

### ISSUE THREAD

**Issue by erikw** [bitsofpancake/spotify-backup#5]
Hi!

When I use this script I often encounter an IncompleteRead error, for different playlists every time. Do you know what causes this?

```console
$ ./spotify-backup.py --format json --token ... outpout.json
...
[05:26:40] Loading playlist: Best of DnB (321 songs)
Traceback (most recent call last):
  File "/home/erikw/dev/spotify-backup/spotify-backup.py", line 169, in <module>
    main()
  File "/home/erikw/dev/spotify-backup/spotify-backup.py", line 146, in main
    playlist['tracks'] = spotify.list(playlist['tracks']['href'], {'limit': 100})
  File "/home/erikw/dev/spotify-backup/spotify-backup.py", line 49, in list
    response = self.get(response['next'])
  File "/home/erikw/dev/spotify-backup/spotify-backup.py", line 36, in get
    return json.load(reader(res))
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/codecs.py", line 489, in read
    newdata = self.stream.read()
  File "/usr/lib/python3.4/http/client.py", line 512, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.4/http/client.py", line 664, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(278101 bytes read, 12098 more expected)

```

**Comment by bitsofpancake** [comment]
There doesn't seem to be a clear reason why this error comes up. How frequently does this happen? I've modified the script to just retry requests in the event of any error... [try it and see if it works](https://github.com/bitsofpancake/spotify-backup/tree/incomplete-read)?

**Comment by erikw** [comment]
Looks much better, the retry works the second time so +1 for you fix branch, works for me.

Unrelated:
If you don't specify a limit on the OAuth token, does it default to 10 usages? Because my tokens keeps stop working after a while, giving 401 unauthorized.

**Comment by bitsofpancake** [comment]
The tokens expire after some time, not sure after how long. That's why the script tries to authenticate every time, to get a fresh token.

**Comment by erikw** [comment]
Aha. In my cronjob'd wrapper script, I pasted a static token that I pass with --token. It sucks if it expires after some time. And letting spotify-backup.py getting a fresh token will open a browser window = not good for scripted jobs? How does the authorization works? Where is the token saved, in a web cache some where?
